name: objective
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^3.1.1
  provider: ^4.3.3
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  dio: ^3.0.10
  fluttertoast: ^7.1.8
  font_awesome_flutter: ^8.11.0
  flutter_phoenix: ^0.1.0
  flutter_svg: ^0.19.3
  get_it: ^6.0.0
  dotted_border: ^1.0.7
  flutter_spinkit: "^4.1.2"
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'images/logo.png'

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icon/
    - images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
